AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create an IAM Role for CodeDeploy

Resources:
  #=================================
  # CodeDeployのロール
  #=================================
  CodeDeployServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "CodeDeployServiceRole"
      # CodeDeployが他のサービスにアクセスする
      Description: "Allow CodeDeploy to call AWS all service"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codedeploy.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
  #=================================
  # CodeDeployに付与予定(Ec2へのアクセス)
  #=================================
  AccessToEC2:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: AccessToEC2
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ec2:Describe*"
            Resource:
              - "*"
      Roles:
        - Ref: CodeDeployServiceRole
  #=================================
  # EC2→S3へのReadAccess
  #=================================
  EC2S3ReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EC2S3ReadOnlyRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
