version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx-repository
    ports:
      - 8080:80
    expose:
      - 8080
    depends_on:
      - app
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: php-fpm-repository
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
